// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoLisW-U1NbF-yYrPxEBkI5Z0XJL2r7Vs',
    appId: '1:797603261713:web:8b7ed03984aa42d61770b0',
    messagingSenderId: '797603261713',
    projectId: 'bollardbros-1afdb',
    authDomain: 'bollardbros-1afdb.firebaseapp.com',
    storageBucket: 'bollardbros-1afdb.firebasestorage.app',
    measurementId: 'G-TFM6HDW2W4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuV0b8LRsF-IhUzI65j6wWLA0ybUqIIWI',
    appId: '1:797603261713:android:66ba24e45e4d9e7d1770b0',
    messagingSenderId: '797603261713',
    projectId: 'bollardbros-1afdb',
    storageBucket: 'bollardbros-1afdb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVDg-MQpD4_SyV5-bnnFe8knZMP8FfGhA',
    appId: '1:797603261713:ios:b74776ffd05c44521770b0',
    messagingSenderId: '797603261713',
    projectId: 'bollardbros-1afdb',
    storageBucket: 'bollardbros-1afdb.firebasestorage.app',
    iosBundleId: 'com.example.iotProjectMobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVDg-MQpD4_SyV5-bnnFe8knZMP8FfGhA',
    appId: '1:797603261713:ios:b74776ffd05c44521770b0',
    messagingSenderId: '797603261713',
    projectId: 'bollardbros-1afdb',
    storageBucket: 'bollardbros-1afdb.firebasestorage.app',
    iosBundleId: 'com.example.iotProjectMobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBoLisW-U1NbF-yYrPxEBkI5Z0XJL2r7Vs',
    appId: '1:797603261713:web:a81e4387891d2a681770b0',
    messagingSenderId: '797603261713',
    projectId: 'bollardbros-1afdb',
    authDomain: 'bollardbros-1afdb.firebaseapp.com',
    storageBucket: 'bollardbros-1afdb.firebasestorage.app',
    measurementId: 'G-PPKMM92331',
  );
}
